<?php

namespace Database\Seeders;

use App\Models\CareerPosition;
use Illuminate\Database\Seeder;

class CareerPositionSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'title_ar' => 'طبيب أسنان عام',
                'title_en' => 'General Dentist',
                'department_ar' => 'القسم الطبي',
                'department_en' => 'Medical Department',
                'location_ar' => 'القاهرة - مدينة نصر',
                'location_en' => 'Cairo - Nasr City',
                'job_type' => 'full_time',
                'experience_level' => '3+ years',
                'summary_ar' => 'تشخيص وعلاج الحالات العامة ومتابعة خطط العلاج الدورية للمرضى.',
                'summary_en' => 'Diagnose and treat general dental cases and follow treatment plans.',
                'description_ar' => "المهام الرئيسية:\n- الكشف الأولي والتشخيص.\n- تنفيذ العلاجات العامة.\n- متابعة الحالات بعد العلاج.\n- توثيق الملف الطبي بدقة.",
                'description_en' => "Responsibilities:\n- Initial diagnosis and checkups.\n- Perform general treatments.\n- Follow up with patients.\n- Keep accurate medical records.",
                'requirements_ar' => "<ul><li>بكالوريوس طب الأسنان</li><li>ترخيص مزاولة</li><li>مهارات تواصل ممتازة</li></ul>",
                'requirements_en' => "<ul><li>Bachelor of Dentistry</li><li>Valid license</li><li>Excellent communication skills</li></ul>",
                'sort_order' => 1,
            ],
            [
                'title_ar' => 'أخصائي تقويم أسنان',
                'title_en' => 'Orthodontic Specialist',
                'department_ar' => 'القسم الطبي',
                'department_en' => 'Medical Department',
                'location_ar' => 'القاهرة - حلوان',
                'location_en' => 'Cairo - Helwan',
                'job_type' => 'part_time',
                'experience_level' => '4+ years',
                'summary_ar' => 'وضع خطط التقويم ومتابعة الحالات الدورية باستخدام أنظمة حديثة.',
                'summary_en' => 'Plan and monitor orthodontic cases using modern techniques.',
                'description_ar' => "المهام:\n- تقييم حالات سوء الإطباق.\n- اختيار نظام التقويم المناسب.\n- متابعة شهرية دقيقة.",
                'description_en' => "Responsibilities:\n- Assess malocclusion cases.\n- Select suitable orthodontic systems.\n- Monthly follow-up.",
                'requirements_ar' => "<ul><li>ماجستير تقويم أو خبرة معتمدة</li><li>خبرة في التقويم الشفاف</li></ul>",
                'requirements_en' => "<ul><li>Orthodontics master degree or equivalent experience</li><li>Experience with clear aligners</li></ul>",
                'sort_order' => 2,
            ],
            [
                'title_ar' => 'أخصائي علاج جذور',
                'title_en' => 'Endodontist',
                'department_ar' => 'القسم الطبي',
                'department_en' => 'Medical Department',
                'location_ar' => 'القاهرة - حدائق القبة',
                'location_en' => 'Cairo - Hadaeq El Qubba',
                'job_type' => 'full_time',
                'experience_level' => '5+ years',
                'summary_ar' => 'إدارة حالات علاج العصب المعقدة باستخدام أجهزة قياس حديثة.',
                'summary_en' => 'Handle advanced root canal cases with modern endodontic tools.',
                'description_ar' => "المهام:\n- تشخيص التهابات العصب.\n- تنفيذ علاج جذور دقيق.\n- التنسيق مع فريق التركيبات.",
                'description_en' => "Responsibilities:\n- Diagnose pulp infections.\n- Perform accurate root canal therapy.\n- Coordinate with prosthodontic team.",
                'requirements_ar' => "<ul><li>خبرة مثبتة في علاج الجذور</li><li>قدرة على التعامل مع الحالات الطارئة</li></ul>",
                'requirements_en' => "<ul><li>Proven endodontic experience</li><li>Emergency case handling skills</li></ul>",
                'sort_order' => 3,
            ],
            [
                'title_ar' => 'طبيب تجميل أسنان',
                'title_en' => 'Cosmetic Dentist',
                'department_ar' => 'القسم الطبي',
                'department_en' => 'Medical Department',
                'location_ar' => 'القاهرة - مدينة نصر',
                'location_en' => 'Cairo - Nasr City',
                'job_type' => 'contract',
                'experience_level' => '4+ years',
                'summary_ar' => 'تنفيذ جلسات تجميل ابتسامة وهوليود سمايل وتبييض الأسنان.',
                'summary_en' => 'Deliver cosmetic smile makeovers and advanced whitening procedures.',
                'description_ar' => "المهام:\n- تقييم جمالي شامل.\n- تنفيذ فينير وعدسات.\n- توجيه المريض للعناية بعد الجلسة.",
                'description_en' => "Responsibilities:\n- Smile aesthetics assessment.\n- Veneers and laminates procedures.\n- Post-treatment guidance.",
                'requirements_ar' => "<ul><li>Portfolio لحالات تجميل</li><li>إتقان التصوير الطبي</li></ul>",
                'requirements_en' => "<ul><li>Strong cosmetic portfolio</li><li>Dental photography skills</li></ul>",
                'sort_order' => 4,
            ],
            [
                'title_ar' => 'مساعد/ة طبيب أسنان',
                'title_en' => 'Dental Assistant',
                'department_ar' => 'التمريض',
                'department_en' => 'Nursing',
                'location_ar' => 'القاهرة - حلوان',
                'location_en' => 'Cairo - Helwan',
                'job_type' => 'full_time',
                'experience_level' => '1+ years',
                'summary_ar' => 'تجهيز العيادات ومساعدة الأطباء أثناء الإجراءات اليومية.',
                'summary_en' => 'Prepare clinics and assist doctors during daily procedures.',
                'description_ar' => "المهام:\n- تجهيز الأدوات قبل الجلسة.\n- دعم الطبيب أثناء العلاج.\n- تعقيم الأدوات بعد الانتهاء.",
                'description_en' => "Responsibilities:\n- Prepare tools before treatment.\n- Chairside assistance.\n- Sterilization after procedures.",
                'requirements_ar' => "<ul><li>خبرة سابقة في عيادات الأسنان</li><li>الالتزام بمعايير التعقيم</li></ul>",
                'requirements_en' => "<ul><li>Previous dental clinic experience</li><li>Strong sterilization discipline</li></ul>",
                'sort_order' => 5,
            ],
            [
                'title_ar' => 'موظف/ة استقبال طبي',
                'title_en' => 'Medical Receptionist',
                'department_ar' => 'الاستقبال',
                'department_en' => 'Reception',
                'location_ar' => 'القاهرة - مدينة نصر',
                'location_en' => 'Cairo - Nasr City',
                'job_type' => 'full_time',
                'experience_level' => '2+ years',
                'summary_ar' => 'إدارة المكالمات والحجوزات والتنسيق بين المرضى والأطباء.',
                'summary_en' => 'Manage calls, bookings, and patient-doctor coordination.',
                'description_ar' => "المهام:\n- استقبال المرضى.\n- تأكيد المواعيد.\n- تحديث بيانات النظام.",
                'description_en' => "Responsibilities:\n- Welcome patients.\n- Confirm schedules.\n- Update system records.",
                'requirements_ar' => "<ul><li>مهارات تواصل ممتازة</li><li>خبرة على أنظمة الحجز</li></ul>",
                'requirements_en' => "<ul><li>Excellent communication</li><li>Booking system experience</li></ul>",
                'sort_order' => 6,
            ],
            [
                'title_ar' => 'مسؤول/ة خدمة عملاء',
                'title_en' => 'Patient Care Specialist',
                'department_ar' => 'خدمة العملاء',
                'department_en' => 'Patient Support',
                'location_ar' => 'القاهرة - حدائق القبة',
                'location_en' => 'Cairo - Hadaeq El Qubba',
                'job_type' => 'part_time',
                'experience_level' => '2+ years',
                'summary_ar' => 'متابعة رضا المرضى والرد على الاستفسارات قبل وبعد الزيارة.',
                'summary_en' => 'Follow patient satisfaction and answer inquiries before/after visits.',
                'description_ar' => "المهام:\n- متابعة التقييمات.\n- حل الشكاوى بسرعة.\n- التنسيق مع الأقسام المختلفة.",
                'description_en' => "Responsibilities:\n- Track reviews and feedback.\n- Resolve complaints quickly.\n- Coordinate with internal teams.",
                'requirements_ar' => "<ul><li>لباقة وسرعة استجابة</li><li>خبرة في خدمة العملاء الطبية</li></ul>",
                'requirements_en' => "<ul><li>Professional communication</li><li>Healthcare support experience</li></ul>",
                'sort_order' => 7,
            ],
            [
                'title_ar' => 'مسؤول تسويق رقمي طبي',
                'title_en' => 'Medical Digital Marketing Specialist',
                'department_ar' => 'التسويق',
                'department_en' => 'Marketing',
                'location_ar' => 'القاهرة - عمل هجين',
                'location_en' => 'Cairo - Hybrid',
                'job_type' => 'contract',
                'experience_level' => '3+ years',
                'summary_ar' => 'إدارة الحملات الرقمية وإنشاء محتوى طبي تسويقي احترافي.',
                'summary_en' => 'Manage digital campaigns and create high-quality medical marketing content.',
                'description_ar' => "المهام:\n- إدارة الإعلانات الممولة.\n- كتابة محتوى السوشيال.\n- تحليل الأداء وتحسين النتائج.",
                'description_en' => "Responsibilities:\n- Paid campaigns management.\n- Social media content production.\n- Performance tracking and optimization.",
                'requirements_ar' => "<ul><li>خبرة بإعلانات Meta/Google</li><li>فهم أخلاقيات التسويق الطبي</li></ul>",
                'requirements_en' => "<ul><li>Meta/Google ads experience</li><li>Medical marketing compliance knowledge</li></ul>",
                'sort_order' => 8,
            ],
        ];

        foreach ($rows as $row) {
            CareerPosition::query()->updateOrCreate(
                ['title_en' => $row['title_en']],
                array_merge($row, ['is_active' => true])
            );
        }
    }
}
